DAISY_HW_IDENTIFIER = "VID:PID=0483:5740"
CLI_PREFIX = "[SEED]:"
FLAGPREFIX = "--"

CMD_GET = "get"
CMD_SET = "set"
CMD_RESET = "reset"
CMD_SEND = "send"
CMD_DATA = "data"

CMD_PORT_SPECIFIED_FLAG = "--p"
CMD_SEND_FLAG_SDRAM = "--sdram"
CMD_SEND_FLAG_QSPI = "--qspi"

RESPONSE_OK = "OK"
RESPONSE_ERR = "ERR"
RESPONSE_WARN = "WARN"
RESPONSE_RDY = "RDY"
RESPONSE_FNSH = "FNSH"

PAD_BYTE = '0'
EOF_FLAG = "stop"
BLOCK_PREFIX_LEN = 4
BLOCKSIZE = 60

CRC_POLYNOMIAL = 0x8408
CRC_INITIAL_VALUE = 0xFFFF
