CLI_PREFIX = "[SEED]:"
FLAGPREFIX = "--"

CMD_GET = "get"
CMD_SET = "set"
CMD_SEND = "send"
CMD_DATA = "data"

CMD_SEND_FLAG_SDRAM = "--sdram"
CMD_SEND_FLAG_QSPI = "--qspi"

RESPONSE_OK = "OK"
RESPONSE_ERR = "ERR"
RESPONSE_WARN = "WARN"
RESPONSE_RDY = "RDY"
RESPONSE_FNSH = "FNSH"

PAD_BYTE = '0'
EOF_FLAG = "stop"
BLOCK_PREFIX_LEN = 4
BLOCKSIZE = 60
